from __future__ import annotations

import asyncio
import collections
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from fastapi import APIRouter, HTTPException

from server.commands import get_command
from server.config import REPO_ROOT

router = APIRouter(prefix="/api/runs", tags=["runs"])

_MAX_HISTORY = 200

# Serial execution queue — automations are not headless and must not overlap.
_queue: asyncio.Queue[Run] = asyncio.Queue()
_worker_task: asyncio.Task[None] | None = None


class RunStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"


class Run:
    __slots__ = ("id", "command", "status", "params", "started_at", "finished_at", "logs", "queue_position", "scheduled")

    def __init__(self, command: str, params: dict[str, Any], *, scheduled: bool = False) -> None:
        self.id: str = uuid.uuid4().hex[:12]
        self.command = command
        self.params = params
        self.status: RunStatus = RunStatus.PENDING
        self.started_at: datetime = datetime.now(timezone.utc)
        self.finished_at: datetime | None = None
        self.logs: str = ""
        self.queue_position: int | None = None  # None when running or done
        self.scheduled: bool = scheduled  # True only for scheduler-triggered runs

    def to_dict(self, include_logs: bool = False) -> dict[str, Any]:
        d: dict[str, Any] = {
            "id": self.id,
            "command": self.command,
            "status": self.status.value,
            "params": self.params,
            "started_at": self.started_at.isoformat(),
            "finished_at": self.finished_at.isoformat() if self.finished_at else None,
            "queue_position": self.queue_position,
        }
        if include_logs:
            d["logs"] = self.logs
        return d


_runs: collections.OrderedDict[str, Run] = collections.OrderedDict()


def _evict_old_runs() -> None:
    """Remove oldest completed runs when history exceeds _MAX_HISTORY."""
    if len(_runs) <= _MAX_HISTORY:
        return
    to_delete = []
    for key, run in _runs.items():
        if len(_runs) - len(to_delete) <= _MAX_HISTORY:
            break
        if run.status in (RunStatus.SUCCESS, RunStatus.FAILED):
            to_delete.append(key)
    for key in to_delete:
        del _runs[key]


def _refresh_queue_positions() -> None:
    """Update queue_position for all PENDING runs based on queue order."""
    pending = [r for r in _runs.values() if r.status == RunStatus.PENDING]
    # The queue drains FIFO, so order in _runs matches queue order.
    for i, run in enumerate(pending):
        run.queue_position = i + 1


async def execute_run(run: Run) -> None:
    """Execute a single run as a subprocess and capture output."""
    cmd = get_command(run.command)
    if cmd is None:
        run.status = RunStatus.FAILED
        run.logs = f"Unknown command: {run.command}"
        run.finished_at = datetime.now(timezone.utc)
        run.queue_position = None
        return

    args = cmd.build_args(run.params)
    run.status = RunStatus.RUNNING
    run.queue_position = None
    _refresh_queue_positions()

    try:
        proc = await asyncio.create_subprocess_exec(
            *args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            cwd=REPO_ROOT,
        )
        stdout, _ = await proc.communicate()
        run.logs = stdout.decode(errors="replace") if stdout else ""
        run.status = RunStatus.SUCCESS if proc.returncode == 0 else RunStatus.FAILED
    except Exception as exc:
        run.logs = str(exc)
        run.status = RunStatus.FAILED
    finally:
        run.finished_at = datetime.now(timezone.utc)
        run.queue_position = None
        # Send Lark notification (non-blocking, errors are swallowed in notify module)
        await asyncio.to_thread(_notify_run, run)


def _notify_run(run: Run) -> None:
    """Send a Lark notification for a completed run (called in a thread)."""
    try:
        from server.notify import notify_run_complete
        notify_run_complete(run)
    except Exception:
        pass  # notification failures must never affect the run result

    # For a successful *scheduled* daily-report, send the xlsx to production chat.
    # Non-scheduled runs (manual API triggers, tests) do NOT deliver to production.
    if run.command == "daily-report" and run.status.value == "success" and run.scheduled:
        try:
            from server.notify import notify_daily_report_file
            report_path = _find_report_from_run(run)
            if report_path:
                notify_daily_report_file(report_path)
        except Exception:
            pass  # file delivery failures must never affect the run result


def _find_report_from_run(run: "Run") -> "Path | None":
    """Locate the daily report file generated by *run*.

    Strategy:
    1. If the run params include a ``date``, look up that exact file.
    2. Otherwise parse the output path from the run logs
       (``Report saved to /path/to/database_report_YYYY_MM_DD.xlsx``).
    3. Fall back to the most recently modified xlsx in the daily-report dir.
    """
    import re
    from pathlib import Path
    from server.config import settings

    daily_dir = settings.output_dir.resolve() / "daily-report"

    # Strategy 1: explicit date param
    if date_str := run.params.get("date"):
        try:
            from datetime import date as _date
            d = _date.fromisoformat(str(date_str))
            p = daily_dir / f"database_report_{d.year}_{d.month:02d}_{d.day:02d}.xlsx"
            if p.exists():
                return p
        except Exception:
            pass

    # Strategy 2: parse log line "Report saved to /abs/path/database_report_*.xlsx"
    if run.logs:
        m = re.search(r"Report saved to (.+database_report_\d{4}_\d{2}_\d{2}\.xlsx)", run.logs)
        if m:
            p = Path(m.group(1))
            if p.exists():
                return p

    # Strategy 3: most recently modified xlsx in the output dir
    candidates = sorted(daily_dir.glob("database_report_*.xlsx"), key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0] if candidates else None


async def _queue_worker() -> None:
    """Background task: drain the queue one run at a time."""
    while True:
        run = await _queue.get()
        try:
            await execute_run(run)
        finally:
            _queue.task_done()


def start_queue_worker() -> None:
    """Start the background queue worker. Call once from app lifespan."""
    global _worker_task
    loop = asyncio.get_running_loop()
    _worker_task = loop.create_task(_queue_worker())


def create_run(command_name: str, params: dict[str, Any], *, scheduled: bool = False) -> Run:
    """Create a Run, enqueue it for serial execution, and return it.

    Set *scheduled=True* for runs created by the internal scheduler (cron).
    Only scheduled runs trigger production deliveries (e.g. sending the daily
    report xlsx to the production chat).
    """
    run = Run(command_name, params, scheduled=scheduled)
    _runs[run.id] = run
    _evict_old_runs()
    _queue.put_nowait(run)
    _refresh_queue_positions()
    return run


@router.get("")
async def list_runs() -> list[dict[str, Any]]:
    return [r.to_dict() for r in reversed(_runs.values())]


@router.get("/{run_id}")
async def get_run(run_id: str) -> dict[str, Any]:
    run = _runs.get(run_id)
    if run is None:
        raise HTTPException(status_code=404, detail="Run not found")
    return run.to_dict(include_logs=True)
